# Generated by Django 5.0.1 on 2024-02-10 08:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="m_2019_List_Of_Fields",
            fields=[
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "reestr_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("comment", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "intern_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("id_district", models.IntegerField(blank=True, null=True)),
                ("id_owner", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("id_type_usage_plan", models.IntegerField(blank=True, null=True)),
                ("id_type_usage_fact", models.IntegerField(blank=True, null=True)),
                ("id_crop_plan", models.IntegerField(blank=True, null=True)),
                ("id_crop_fact", models.IntegerField(blank=True, null=True)),
                ("id_crop_sort_plan", models.IntegerField(blank=True, null=True)),
                ("id_crop_sort_fact", models.IntegerField(blank=True, null=True)),
                (
                    "biochem_fact",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("harvest_fact", models.FloatField(blank=True, null=True)),
                ("harvest_forecast", models.FloatField(blank=True, null=True)),
                ("pesticides", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "fertilizers",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("sowing_date", models.DateField(blank=True, null=True)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("inspected", models.BooleanField()),
                ("hash_unique", models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                "db_table": "2019_list_of_fields",
                "managed": False,
            },
        ),
    ]
